# Generated by Django 3.0.2 on 2020-12-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0005_auto_20201130_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
    ]
